// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/component/ReactWindowStickyCells":{"path":"component/react-window-sticky-cells","id":"docs/component/ReactWindowStickyCells","parentId":"DocLayout"},"docs/component/PopoverDialog":{"path":"component/popover-dialog","id":"docs/component/PopoverDialog","parentId":"DocLayout"},"docs/component/Relation":{"path":"component/relation","id":"docs/component/Relation","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/jxd/Desktop/前端项目/前端项目/react-window-table/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/jxd/Desktop/前端项目/前端项目/react-window-table/.dumi/tmp/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/jxd/Desktop/前端项目/前端项目/react-window-table/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/component/ReactWindowStickyCells': React.lazy(() => import(/* webpackChunkName: "docs__component__ReactWindowStickyCells.md" */'/Users/jxd/Desktop/前端项目/前端项目/react-window-table/docs/component/ReactWindowStickyCells.md')),
'docs/component/PopoverDialog': React.lazy(() => import(/* webpackChunkName: "docs__component__PopoverDialog.md" */'/Users/jxd/Desktop/前端项目/前端项目/react-window-table/docs/component/PopoverDialog.md')),
'docs/component/Relation': React.lazy(() => import(/* webpackChunkName: "docs__component__Relation.md" */'/Users/jxd/Desktop/前端项目/前端项目/react-window-table/docs/component/Relation.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/jxd/Desktop/前端项目/前端项目/react-window-table/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/jxd/Desktop/前端项目/前端项目/react-window-table/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
