// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/jxd/Desktop/前端项目/前端项目/react-window-table/node_modules/dumi/theme-default/slots/PreviewerActionsExtra/index.js';
